### ISSUE TITLE
word not in biowordwec

### ISSUE THREAD

**Issue by Markin-Wang** [ivonajdenkoska/variational-xray-report-gen#2]
Hi, thanks for sharing the code.
May I ask you how to process the words in MIMIC vocabulary that are not existed in the biowordvec. For example, word 'cannot'.

Can you provide the file "bio_word2vec_weights.pkl"?

Thanks.

**Comment by yuxue-liu** [comment]
@Markin-Wang I meet the same question, have you solved it yet?

**Comment by Markin-Wang** [comment]
> @Markin-Wang I meet the same question, have you solved it yet?

Hi, as you can see, I didn't receive the reply from the authors, so I turned to other methods.

**Comment by ivonajdenkoska** [comment]
Hi, check the answer in the closed issue: https://github.com/ivonajdenkoska/variational-xray-report-gen/issues/1.
